name: MyApp
options:
  bundleIdPrefix: com.example
targets:
  MyApp:
    type: application
    platform: macOS
    deploymentTarget: "10.13"
    sources: src/MyApp
    prebuildScripts:
      - name: Sourcery
        path: ./scripts/sourcery.sh
      - name: Format
        path: ./scripts/format.sh
    dependencies:
      - carthage: Dip
      - carthage: Snapkit
  